import assert from 'node:assert/strict';
import { existsSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { applicationSites, getApplicationSites, retiredApplicationSites } from '../src/lib/applications/registry.js';
import { validateFeaturedProjects } from '../src/lib/applications/project-selection.js';
import { validateFeaturedArticles } from '../src/lib/drawing-board/rules.js';

const applicationDownloadHeaders = `# Generated by scripts/application-build.mjs for every included application.
# Cloudways must forward PDF requests to Apache for this rule to take effect.
<IfModule mod_headers.c>
    <FilesMatch "(?i)\\.pdf$">
        Header always set X-Robots-Tag "noindex"
    </FilesMatch>
</IfModule>
`;

export function validateApplicationFiles(root) {
  const sitesRoot = join(root, 'src/sites');
  const folders = readdirSync(sitesRoot, { withFileTypes: true }).filter((entry) => entry.isDirectory()).map(({ name }) => name);
  assert.deepEqual(folders.sort(), [...applicationSites].sort(), 'Every src/sites directory must be registered in src/lib/applications/registry.js.');
  const requiredCopy = {
    home: ['title', 'description', 'headline', 'role', 'experience', 'location', 'projectsHeading', 'workButton', 'aboutHeading', 'whoHeading', 'who', 'whatHeading', 'what', 'aboutButton', 'storiesButton'],
    caseStudies: ['title', 'description', 'headline', 'introduction']
  };

  for (const site of retiredApplicationSites) {
    for (const path of [`src/pages/${site}.astro`, `src/sites/${site}`, `public/${site}`]) {
      assert.ok(!existsSync(join(root, path)), `${site}: remove retired application source at ${path}`);
    }
  }

  for (const site of applicationSites) {
    const directory = join(sitesRoot, site);
    for (const file of ['site.json', 'projects.json', 'articles.json', 'README.md', 'application-brief.md']) {
      assert.ok(existsSync(join(directory, file)), `${site}: missing src/sites/${site}/${file}`);
    }
    assert.ok(existsSync(join(root, 'public', site, 'resume-carl-avidano.pdf')), `${site}: missing its independent résumé asset.`);
    assert.ok(!existsSync(join(root, 'public', site, '.htaccess')), `${site}: application download headers are generated by scripts/application-build.mjs; do not maintain a separate .htaccess copy.`);
    assert.ok(!existsSync(join(directory, 'portfolio')), `${site}: case studies must use the shared src/content/portfolio source, not application copies.`);
    const selection = JSON.parse(readFileSync(join(directory, 'projects.json'), 'utf8'));
    assert.deepEqual(Object.keys(selection), ['featured'], `${site}: projects.json only curates projects; keep case-study copy in the shared MDX.`);
    const projectSlugs = readdirSync(join(root, 'src/content/portfolio')).filter((file) => file.endsWith('.mdx')).map((file) => file.slice(0, -4));
    validateFeaturedProjects(selection.featured, projectSlugs, site);
    assert.ok(!existsSync(join(directory, 'drawing-board')), `${site}: articles must use the shared src/content/drawing-board source, not application copies.`);
    const articles = JSON.parse(readFileSync(join(directory, 'articles.json'), 'utf8'));
    assert.deepEqual(Object.keys(articles), ['featured'], `${site}: articles.json only curates articles; keep copy in the shared MDX.`);
    const articleIds = readdirSync(join(root, 'src/content/drawing-board')).filter((file) => file.endsWith('.mdx')).map((file) => file.slice(0, -4));
    validateFeaturedArticles(articles.featured, articleIds, site);

    const copy = JSON.parse(readFileSync(join(directory, 'site.json'), 'utf8'));
    for (const field of ['introduction', 'panelHeading', 'profileGreeting']) {
      if (copy.home?.[field] !== undefined) {
        assert.ok(typeof copy.home[field] === 'string' && copy.home[field].trim(), `${site}: optional home.${field} must contain text when provided.`);
      }
    }
    const hasIntroPanel = Boolean(copy.home?.panelHeading);
    assert.equal(existsSync(join(directory, 'Hero.astro')), hasIntroPanel, `${site}: Hero.astro and home.panelHeading must be provided together for a branded introduction.`);
    if (hasIntroPanel) {
      for (const theme of ['light', 'dark']) {
        assert.ok(existsSync(join(root, 'public', site, `${site}-logo-${theme}.svg`)), `${site}: missing official ${theme}-mode logo.`);
      }
    }
    for (const [section, fields] of Object.entries(requiredCopy)) {
      for (const field of fields) {
        assert.ok(typeof copy[section]?.[field] === 'string' && copy[section][field].trim(), `${site}: missing text at site.json → ${section}.${field}`);
      }
    }
  }
}

function removeFinderFiles(directory) {
  for (const entry of readdirSync(directory, { withFileTypes: true })) {
    const path = join(directory, entry.name);
    if (entry.isDirectory()) removeFinderFiles(path);
    else if (entry.name === '.DS_Store') rmSync(path);
  }
}

export function cleanApplicationOutput(directory, { includeDrafts = false } = {}) {
  const included = getApplicationSites({ includeDrafts });
  for (const site of applicationSites.filter((id) => !included.includes(id))) {
    // Astro also copies public/ assets; omitting routes alone would expose draft PDFs.
    rmSync(join(directory, site), { recursive: true, force: true });
  }
  removeFinderFiles(directory);
  for (const site of included) {
    writeFileSync(join(directory, site, '.htaccess'), applicationDownloadHeaders);
  }
  for (const site of retiredApplicationSites) {
    assert.ok(!existsSync(join(directory, site)), `${site}: retired application appears in the build output`);
  }
  writeFileSync(join(directory, '.retired-applications.json'), JSON.stringify(retiredApplicationSites, null, 2) + '\n');
}

/** @returns {import('astro').AstroIntegration} */
export default function applicationBuild({ includeDrafts = false } = {}) {
  return {
    name: 'application-sites',
    hooks: {
      'astro:config:setup': ({ config }) => {
        validateApplicationFiles(fileURLToPath(config.root));
      },
      'astro:build:done': ({ dir, logger }) => {
        cleanApplicationOutput(fileURLToPath(dir), { includeDrafts });
        logger.info(`Included applications: ${getApplicationSites({ includeDrafts }).join(', ') || 'none'}${includeDrafts ? ' (local review)' : ''}.`);
      }
    }
  };
}
